# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ef543fdc855f782d2a5cadc95f4864f9c1036396705e50fde8167ad6946a54de983bb8be918a2257158243ab0f013af93d0297b70903bf7dc4eb59197593eba

test:
  secret_key_base: 4d77a7dc86ea79c8166776c621656276a10cbb337dacc1e27d33fddf9878c7900b4eb940bb04d9e9c093160b07eb224ed77186b182305a3f84e23d167b0c44c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
